AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket
Parameters:
  BucketName:
    Type: String
    Description: creat unique S3 bucket name in the world(mandatory change name required) 
    Default: xxxxxxs3location
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket
