CREATE VIEW apdb.rpt_view_link_mkt AS
select Distinct
     YM &'|'& Defined_MKT &'|'& BrandCode &'|'& CityCode &'|'& InsID as Key_CPA,
     YM &'|'& Defined_MKT &'|'& BrandCode &'|'& If(isnull(IMS_CityCode),IMS_CityCode,'NoIMSCity') as Key_IMS,
     InsID,
     InsID_Aspen,
     YM, 
     Defined_MKT, 
     BrandCode, 
     CityCode,
     RSM_Code,
     DSM_Code, 
     MR_Code, 
     DSM, 
     RSM, 
     MR, 
     Team, 
     Region, 
     RSD_Code, 
     RSD,
     If(isnull(BrandCode),'NULL',Upper(BrandCode)) as BRANDCODE_ACCESS,
     If(isnull(ProvinceCode),'NULL',ProvinceCode)  as PROVINCE_ACCESS,
     If(isnull(RSM_Code),'NULL',Upper(RSM_Code)) as RSMCODE_ACCESS ,
     If(isnull(DSM_Code),'NULL',Upper(DSM_Code)) as DSMCODE_ACCESS ,
     If(isnull(RSD_Code),'NULL',Upper(RSD_Code)) as RSDCODE_ACCESS
from apdb.link_dim_main_mkt;