select * from dag_dependence;
select * from dim_dag;
select * from dim_email;
select * from dim_task;
select * from dim_job;
select * from dim_job_params;
select * from fact_dag_details;
select * from fact_task_details;
select * from fact_job_details;
