AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Type: String
    Default: CEDC
    Description: Please input project name and this name will be used in each output variables
  ENV:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - PROD
    Description: Please input ENV
  ConName:
    Type: String
    Description: Glue connection name.
    Default: s3-connection
  CrawlerName:
    Type: String
    Default: s3crawler
  CrawlerRoleArn:
    Type: String
    Default: arn:aws:iam::064055545018:role/GlueCrawlerAdminRole
  S3Path:
    Type: String
    Default: s3://bkt-dfk/workspace/tmp/
  DatabaseName:
    Type: String
    Default: db_elt
  TablePrefix:
    Type: String
    Default: myprefix_
  StackName:
    Type: String
    Default: connection-network-s3
Resources:
  MyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !Ref CrawlerRoleArn
      Targets:
        S3Targets:
        - Path: !Ref S3Path
          ConnectionName: !ImportValue 
            Fn::Sub: "${ProjectName}-${ENV}-glue-connection-${ConName}"
      DatabaseName: !Ref DatabaseName
      TablePrefix: !Ref TablePrefix
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
Outputs:
  CrawlerName:
    Value: !Ref MyCrawler
    Export:
      # Naming Conventions: <project name>-<ENV>-<service name>-<type>-<name>
      Name: !Sub '${ProjectName}-${ENV}-glue-crawler-${CrawlerName}'
#      Name: !Sub '${AWS::StackName}-${CrawlerName}'