Parameters:
  ProjectName:
    Type: String
    Default: CEDC
    Description: Please input project name and this name will be used in each output variables
  ENV:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - PROD
    Description: Please input ENV
  PostgresConnName:
    Type: String
    Description: Glue Postgres connection name.
    Default: postgre-conn
  PostgresConnVpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC to use for the Glue connection
  PostgresConnSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the subnet to use for the Glue connection, SubnetId needs to be consistent with AvailabilityZone
  PostgresConnSecurityGroupIdList:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security group IDs to use for the Glue connection
  PostgresConnJDBCConnectionURL:
    Type: String
    Description: The JDBC connection URL for the PostgreSQL database
    Default: jdbc:postgresql://postgresrdsdb.cteunoyun6vy.ap-northeast-1.rds.amazonaws.com:5432/postgres
  PostgresConnUsername:
    Type: String
    Description: The username for the PostgreSQL database
    Default: pgadmin
  PostgresConnPassword:
    Type: String
    NoEcho: true
    Description: The password for the PostgreSQL database
    Default: password123
  PostgresConnAvailabilityZone:
    Type: String
    NoEcho: true
    Description: The password for the PostgreSQL database
    Default: ap-northeast-1c

Resources:
  MyGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      ConnectionInput:
        Name: !Ref PostgresConnName
        ConnectionType: "JDBC"
        ConnectionProperties:
          JDBC_CONNECTION_URL: !Ref PostgresConnJDBCConnectionURL
          VPC_ID: !Ref PostgresConnVpcId
          USERNAME: !Ref PostgresConnUsername
          PASSWORD: !Ref PostgresConnPassword
          JDBC_ENFORCE_SSL: false
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref PostgresConnAvailabilityZone
          SubnetId: !Ref PostgresConnSubnetId
          SecurityGroupIdList: !Ref PostgresConnSecurityGroupIdList

Outputs:
  ConnectionName:
    Description: Name of the Glue connection.
    Value: !Ref MyGlueConnection
    Export:
      # Naming Conventions: <project name>-<ENV>-<service name>-<type>-<name>
      Name: !Sub '${ProjectName}-${ENV}-glue-connection-${PostgresConnName}'
#      Name: !Sub "${AWS::StackName}-MyGlueConnection"
