Description: "AWS Glue Job Template"
Parameters:
  GlueName:
    Type: String
    Description: Glue Name
  ScriptLocation:
    Type: String
    Description: Script Location
  CommonPackageLocation:
    Type: String
    Description: Common Package Location
  JarLocation:
    Type: String
    Description: Package Location
  TempS3Location:
    Type: String
    Description: Temp S3 Location
  MaxConcurrentRuns:
    Type: String
    Description: Max Current Runs
  MaxRetries:
    Type: String
    Description: Max Retries
  WorkerType:
    Type: String
    Description: Worker Type
  NumberOfWorkers:
    Type: String
    Description: Number Of Workers
  GlueJobName:
    Type: String
    Description: Glue Job Name
  IAMRole:
    Type: String
    Description: Glue Job IAM Role
  GlueVersionName:
    Type: String
    Description: Glue Version Name
  GlueConnectionName:
    Type: String
    Description: Glue Connection Name
  APPName:
    Type: String
    Description: Glue Application Name
  EmailAddress:
    Type: String
    Description: Glue Email Address
  Layer:
    Type: String
    Description: Glue Layer Name

Resources:
  MyJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: !Ref GlueName
        ScriptLocation: !Ref ScriptLocation
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-enable"
        "--extra-py-files": !Ref CommonPackageLocation
        "--enable-glue-datacatalog": ""
        "--enable-metrics": ""
        "--extra-jars": !Ref JarLocation
        "--TempDir": !Ref TempS3Location
      ExecutionProperty:
        MaxConcurrentRuns: !Ref MaxConcurrentRuns
      MaxRetries: !Ref MaxRetries
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      Name: !Ref GlueJobName
      Role: !Ref IAMRole
      GlueVersion: !Ref GlueVersionName
      Connections:
        Connections:
          - !Ref GlueConnectionName
      Tags:
        APPName: !Ref APPName
        EMAIL: !Ref EmailAddress
        Layer: !Ref Layer
