AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CrawlerName:
    Type: String
    Default: s3crawler
  CrawlerRoleArn:
    Type: String
    Default: arn:aws:iam::064055545018:role/GlueCrawlerAdminRole
  S3Path:
    Type: String
    Default: s3://bkt-dfk/workspace/tmp/
  DatabaseName:
    Type: String
    Default: db_elt
  TablePrefix:
    Type: String
    Default: myprefix_
  StackName:
    Type: String
    Default: connection-network-s3
Resources:
  MyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CrawlerName
      Role: !Ref CrawlerRoleArn
      Targets:
        S3Targets:
        - Path: !Ref S3Path
          ConnectionName: !ImportValue 
            Fn::Sub: "${StackName}-GlueConnection"
      DatabaseName: !Ref DatabaseName
      TablePrefix: !Ref TablePrefix
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE
Outputs:
  CrawlerName:
    Value: !Ref MyCrawler
    Export:
      Name: !Sub '${AWS::StackName}-${CrawlerName}'