Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC to use for the Glue connection
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the subnet to use for the Glue connection, SubnetId needs to be consistent with AvailabilityZone
  SecurityGroupIdList:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security group IDs to use for the Glue connection
  JDBCConnectionURL:
    Type: String
    Description: The JDBC connection URL for the PostgreSQL database
    Default: jdbc:postgresql://postgresrdsdb.cteunoyun6vy.ap-northeast-1.rds.amazonaws.com:5432/postgres
  Username:
    Type: String
    Description: The username for the PostgreSQL database
    Default: pgadmin
  Password:
    Type: String
    NoEcho: true
    Description: The password for the PostgreSQL database
    Default: password123
  AvailabilityZone:
    Type: String
    NoEcho: true
    Description: The password for the PostgreSQL database
    Default: ap-northeast-1c

Resources:
  MyGlueConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      ConnectionInput:
        Name: "my-connection-name"
        ConnectionType: "JDBC"
        ConnectionProperties:
          JDBC_CONNECTION_URL: !Ref JDBCConnectionURL
          VPC_ID: !Ref VpcId
          USERNAME: !Ref Username
          PASSWORD: !Ref Password
          JDBC_ENFORCE_SSL: false
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref AvailabilityZone
          SubnetId: !Ref SubnetId
          SecurityGroupIdList: !Ref SecurityGroupIdList

Outputs:
  ConnectionName:
    Description: Name of the Glue connection.
    Value: !Ref MyGlueConnection
    Export:
      Name: !Sub "${AWS::StackName}-MyGlueConnection"
